/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import ConnectDataBase.ConnectDataBase;
import Controleur.ControleurVueEntree;
import Controleur.SubJTable;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author BlackJKL
 */
public class F_optRechEnt extends javax.swing.JDialog {

    private boolean UneDate;
    private boolean DeuxDate;
    private boolean DateInf;
    private boolean DateSup;
    private boolean Fournis;
    private boolean Produit;
    private Statement st;
    private ResultSet rs;
    private Connection con;
    String entete[] = {"Numéro d'entrée", "Date d'entrée", "Quantité", "Prix unitaire", "Fournisseur", "Article"};
    DefaultTableModel dtm = new DefaultTableModel(null, entete);

    /**
     * Creates new form F_optRechEnt
     */
    public F_optRechEnt(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        //imagePanel1.setImage(new ImageIcon(this.getClass().getResource("/Icons/B1.PNG")).getImage());
        TabEntrer.setDefaultRenderer(Object.class, new SubJTable());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imagePanel1 = new picturepanel.ImagePanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        rad1 = new javax.swing.JRadioButton();
        rad3 = new javax.swing.JRadioButton();
        rad4 = new javax.swing.JRadioButton();
        rad2 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        radFour = new javax.swing.JRadioButton();
        cmbfour = new javax.swing.JComboBox();
        radProd = new javax.swing.JRadioButton();
        cmbprod = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Zdate = new com.toedter.calendar.JDateChooser();
        Zdate1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabEntrer = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        jPanel2.setOpaque(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setOpaque(false);

        rad1.setBackground(new java.awt.Color(255, 255, 255));
        rad1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rad1.setText("Une date");
        rad1.setOpaque(false);
        rad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad1ActionPerformed(evt);
            }
        });

        rad3.setBackground(new java.awt.Color(255, 255, 255));
        rad3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rad3.setText("Avant une date");
        rad3.setOpaque(false);
        rad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad3ActionPerformed(evt);
            }
        });

        rad4.setBackground(new java.awt.Color(255, 255, 255));
        rad4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rad4.setText("Après une dates");
        rad4.setOpaque(false);
        rad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad4ActionPerformed(evt);
            }
        });

        rad2.setBackground(new java.awt.Color(255, 255, 255));
        rad2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rad2.setText("Entre deux dates");
        rad2.setOpaque(false);
        rad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rad1)
                    .addComponent(rad3)
                    .addComponent(rad4)
                    .addComponent(rad2))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rad1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rad3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rad4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rad2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setOpaque(false);

        radFour.setBackground(new java.awt.Color(255, 255, 255));
        radFour.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        radFour.setText("Fournisseur :");
        radFour.setOpaque(false);
        radFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radFourActionPerformed(evt);
            }
        });

        cmbfour.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        radProd.setBackground(new java.awt.Color(255, 255, 255));
        radProd.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        radProd.setText("Le produit :");
        radProd.setOpaque(false);
        radProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radProdActionPerformed(evt);
            }
        });

        cmbprod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(radFour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbfour, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(radProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbprod, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radFour)
                    .addComponent(cmbfour, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radProd)
                    .addComponent(cmbprod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel6.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel1.setText("Du :");

        Zdate.setForeground(new java.awt.Color(0, 102, 102));
        Zdate.setDateFormatString("yyyy-MM-dd");
        Zdate.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Zdate.setOpaque(false);

        Zdate1.setForeground(new java.awt.Color(0, 102, 102));
        Zdate1.setDateFormatString("yyyy-MM-dd");
        Zdate1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Zdate1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setText("Au :");

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/1623.png"))); // NOI18N
        jButton1.setText("Rechercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 204));
        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/redo.png"))); // NOI18N
        jButton2.setText("Actueliser");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Zdate, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Zdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Zdate, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Zdate1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabEntrer.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TabEntrer.setForeground(new java.awt.Color(0, 102, 153));
        TabEntrer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro d'entrée", "Date d'entrée", "Quantité", "Prix unitaire", "Fournisseur", "Article"
            }
        ));
        jScrollPane1.setViewportView(TabEntrer);

        jButton3.setBackground(new java.awt.Color(0, 153, 204));
        jButton3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/print.gif"))); // NOI18N
        jButton3.setText("Imprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout imagePanel1Layout = new javax.swing.GroupLayout(imagePanel1);
        imagePanel1.setLayout(imagePanel1Layout);
        imagePanel1Layout.setHorizontalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        imagePanel1Layout.setVerticalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ControleurVueEntree c = new ControleurVueEntree(((JTextField) Zdate.getDateEditor().getUiComponent()).getText(), ((JTextField) Zdate1.getDateEditor().getUiComponent()).getText(), UneDate, DeuxDate, DateInf, DateSup, Fournis, Produit, "", "");
        /*
         * c.remplirTableau();
         */
        TabEntrer.setModel(dtm);
        ((JTextField) Zdate.getDateEditor().getUiComponent()).setText(null);
        ((JTextField) Zdate1.getDateEditor().getUiComponent()).setText(null);
        Zdate.setEnabled(false);
        Zdate1.setEnabled(false);
        jButton1.setEnabled(false);
        cmbfour.setSelectedIndex(0);
        cmbfour.setEnabled(false);
        cmbprod.setSelectedIndex(0);
        cmbprod.setEnabled(false);
        rad1.setSelected(false);
        rad2.setSelected(false);
        rad3.setSelected(false);
        rad4.setSelected(false);
        radFour.setSelected(false);
        radProd.setSelected(false);
        UneDate = true;
        DeuxDate = false;
        DateInf = false;
        DateSup = false;
        Fournis = false;
        Produit = false;
        ((JTextField) Zdate.getDateEditor().getUiComponent()).requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ControleurVueEntree c = new ControleurVueEntree(((JTextField) Zdate.getDateEditor().getUiComponent()).getText(), ((JTextField) Zdate1.getDateEditor().getUiComponent()).getText(), UneDate, DeuxDate, DateInf, DateSup, Fournis, Produit, cmbfour.getSelectedItem().toString(), cmbprod.getSelectedItem().toString());
        c.Rechercher();
        TabEntrer.setModel(c.getDtm());        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (UneDate == true && Fournis == false && Produit == false) {
            try {
                con = new ConnectDataBase().getConnetion();
                String report = "D:\\jkl\\Logiciel\\java\\jordie\\mes application java\\JStore\\src\\Rapport\\EntUneDate.jrxml";
                JasperReport jr = JasperCompileManager.compileReport(report);
                Map parametre = new HashMap();
                parametre.put("DatePar", ((JTextField) Zdate.getDateEditor().getUiComponent()).getText());
                JasperPrint jp = JasperFillManager.fillReport(jr, parametre, con);
                JRViewer viewer = new JRViewer(jp);
                //JasperReport jr=JasperCompileManager.compileReport(report);
                //JasperPrint jp=JasperFillManager.fillReport(jr, null, con);
                JasperViewer.viewReport(jp);
                viewer.setOpaque(true);
                viewer.setVisible(true);
                F_ListProd Lprod = new F_ListProd(new javax.swing.JFrame(), true);
                Lprod.jScrollPane1.add(viewer);
                Lprod.jScrollPane1.setViewportView(viewer);
                Lprod.setVisible(true);
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, "Erreur d'élaboration de rapport d'entrée.", "JStore : Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } else if (DeuxDate == true && Fournis == false && Produit == false) {
            try {
                con = new ConnectDataBase().getConnetion();
                String report = "D:\\jkl\\Logiciel\\java\\jordie\\mes application java\\JStore\\src\\Rapport\\EntDeuxDate.jrxml";
                JasperReport jr = JasperCompileManager.compileReport(report);
                Map parametre = new HashMap();
                parametre.put("Date1", ((JTextField) Zdate.getDateEditor().getUiComponent()).getText());
                parametre.put("Date2", ((JTextField) Zdate1.getDateEditor().getUiComponent()).getText());
                JasperPrint jp = JasperFillManager.fillReport(jr, parametre, con);
                JRViewer viewer = new JRViewer(jp);
                viewer.setOpaque(true);
                viewer.setVisible(true);
                F_ListProd Lprod = new F_ListProd(new javax.swing.JFrame(), true);
                Lprod.jScrollPane1.add(viewer);
                Lprod.jScrollPane1.setViewportView(viewer);
                Lprod.setVisible(true);
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, "Erreur d'élaboration de rapport d'entrée.", "JStore : Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } else if (DateInf == true && Fournis == false && Produit == false) {
            try {
                con = new ConnectDataBase().getConnetion();
                String report = "D:\\jkl\\Logiciel\\java\\jordie\\mes application java\\JStore\\src\\EtatSortie\\EntDateInf.jrxml";
                JasperReport jr = JasperCompileManager.compileReport(report);
                Map parametre = new HashMap();
                parametre.put("DateInf", ((JTextField) Zdate.getDateEditor().getUiComponent()).getText());
                JasperPrint jp = JasperFillManager.fillReport(jr, parametre, con);
                JRViewer viewer = new JRViewer(jp);
                viewer.setOpaque(true);
                viewer.setVisible(true);
                F_ListProd Lprod = new F_ListProd(new javax.swing.JFrame(), true);
                Lprod.jScrollPane1.add(viewer);
                Lprod.jScrollPane1.setViewportView(viewer);
                Lprod.setVisible(true);
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, "Erreur d'élaboration de rapport d'entrée.", "JStore : Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } else if (DateSup == true && Fournis == false && Produit == false) {
            try {
                con = new ConnectDataBase().getConnetion();
                String report = "D:\\jkl\\Logiciel\\java\\jordie\\mes application java\\JStore\\src\\EtatSortie\\EntDateSup.jrxml";
                JasperReport jr = JasperCompileManager.compileReport(report);
                Map parametre = new HashMap();
                parametre.put("DateSup", ((JTextField) Zdate.getDateEditor().getUiComponent()).getText());
                JasperPrint jp = JasperFillManager.fillReport(jr, parametre, con);
                JRViewer viewer = new JRViewer(jp);
                viewer.setOpaque(true);
                viewer.setVisible(true);
                F_ListProd Lprod = new F_ListProd(new javax.swing.JFrame(), true);
                Lprod.jScrollPane1.add(viewer);
                Lprod.jScrollPane1.setViewportView(viewer);
                Lprod.setVisible(true);
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, "Erreur d'élaboration de rapport d'entrée.", "JStore : Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } else if (UneDate == true && Fournis == true && Produit == false) {
            try {
                con = new ConnectDataBase().getConnetion();
                String report = "D:\\jkl\\Logiciel\\java\\jordie\\mes application java\\JStore\\src\\EtatSortie\\EntUneDateFour.jrxml";
                JasperReport jr = JasperCompileManager.compileReport(report);
                Map parametre = new HashMap();
                parametre.put("Date1", ((JTextField) Zdate.getDateEditor().getUiComponent()).getText());
                parametre.put("Four", cmbfour.getSelectedItem().toString());
                JasperPrint jp = JasperFillManager.fillReport(jr, parametre, con);
                JRViewer viewer = new JRViewer(jp);
                viewer.setOpaque(true);
                viewer.setVisible(true);
                F_ListProd Lprod = new F_ListProd(new javax.swing.JFrame(), true);
                Lprod.jScrollPane1.add(viewer);
                Lprod.jScrollPane1.setViewportView(viewer);
                Lprod.setVisible(true);
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, "Erreur d'élaboration de rapport d'entrée.", "JStore : Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } else if (DeuxDate == true && Fournis == true && Produit == false) {
            try {
                con = new ConnectDataBase().getConnetion();
                String report = "D:\\jkl\\Logiciel\\java\\jordie\\mes application java\\JStore\\src\\EtatSortie\\EntDeuxDateFour.jrxml";
                JasperReport jr = JasperCompileManager.compileReport(report);
                Map parametre = new HashMap();
                parametre.put("Date1", ((JTextField) Zdate.getDateEditor().getUiComponent()).getText());
                parametre.put("Date2", ((JTextField) Zdate1.getDateEditor().getUiComponent()).getText());
                parametre.put("Four", cmbfour.getSelectedItem().toString());
                JasperPrint jp = JasperFillManager.fillReport(jr, parametre, con);
                JRViewer viewer = new JRViewer(jp);
                viewer.setOpaque(true);
                viewer.setVisible(true);
                F_ListProd Lprod = new F_ListProd(new javax.swing.JFrame(), true);
                Lprod.jScrollPane1.add(viewer);
                Lprod.jScrollPane1.setViewportView(viewer);
                Lprod.setVisible(true);
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, "Erreur d'élaboration de rapport d'entrée.", "JStore : Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } else if (DateInf == true && Fournis == true && Produit == false) {
            try {
                con = new ConnectDataBase().getConnetion();
                String report = "D:\\jkl\\Logiciel\\java\\jordie\\mes application java\\JStore\\src\\EtatSortie\\EntDateInfFour.jrxml";
                JasperReport jr = JasperCompileManager.compileReport(report);
                Map parametre = new HashMap();
                parametre.put("DateInf", ((JTextField) Zdate.getDateEditor().getUiComponent()).getText());
                parametre.put("Four", cmbfour.getSelectedItem().toString());
                JasperPrint jp = JasperFillManager.fillReport(jr, parametre, con);
                JRViewer viewer = new JRViewer(jp);
                viewer.setOpaque(true);
                viewer.setVisible(true);
                F_ListProd Lprod = new F_ListProd(new javax.swing.JFrame(), true);
                Lprod.jScrollPane1.add(viewer);
                Lprod.jScrollPane1.setViewportView(viewer);
                Lprod.setVisible(true);
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, "Erreur d'élaboration de rapport d'entrée.", "JStore : Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } else if (DateSup == true && Fournis == true && Produit == false) {
            try {
                con = new ConnectDataBase().getConnetion();
                String report = "D:\\jkl\\Logiciel\\java\\jordie\\mes application java\\JStore\\src\\EtatSortie\\EntDateSupFour.jrxml";
                JasperReport jr = JasperCompileManager.compileReport(report);
                Map parametre = new HashMap();
                parametre.put("DateSup", ((JTextField) Zdate.getDateEditor().getUiComponent()).getText());
                parametre.put("Four", cmbfour.getSelectedItem().toString());
                JasperPrint jp = JasperFillManager.fillReport(jr, parametre, con);
                JRViewer viewer = new JRViewer(jp);
                viewer.setOpaque(true);
                viewer.setVisible(true);
                F_ListProd Lprod = new F_ListProd(new javax.swing.JFrame(), true);
                Lprod.jScrollPane1.add(viewer);
                Lprod.jScrollPane1.setViewportView(viewer);
                Lprod.setVisible(true);
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, "Erreur d'élaboration de rapport d'entrée.", "JStore : Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } else if (UneDate == true && Fournis == false && Produit == true) {
            try {
                con = new ConnectDataBase().getConnetion();
                String report = "D:\\jkl\\Logiciel\\java\\jordie\\mes application java\\JStore\\src\\EtatSortie\\EntUneDateProd.jrxml";
                JasperReport jr = JasperCompileManager.compileReport(report);
                Map parametre = new HashMap();
                parametre.put("Date1", ((JTextField) Zdate.getDateEditor().getUiComponent()).getText());
                parametre.put("Prod", cmbprod.getSelectedItem().toString());
                JasperPrint jp = JasperFillManager.fillReport(jr, parametre, con);
                JRViewer viewer = new JRViewer(jp);
                viewer.setOpaque(true);
                viewer.setVisible(true);
                F_ListProd Lprod = new F_ListProd(new javax.swing.JFrame(), true);
                Lprod.jScrollPane1.add(viewer);
                Lprod.jScrollPane1.setViewportView(viewer);
                Lprod.setVisible(true);
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, "Erreur d'élaboration de rapport d'entrée.", "JStore : Erreur", JOptionPane.ERROR_MESSAGE);
            }
        }else if (DeuxDate == true && Fournis == false && Produit == true) {
            try {
                con = new ConnectDataBase().getConnetion();
                String report = "D:\\jkl\\Logiciel\\java\\jordie\\mes application java\\JStore\\src\\EtatSortie\\EntDeuxDateProd.jrxml";
                JasperReport jr = JasperCompileManager.compileReport(report);
                Map parametre = new HashMap();
                parametre.put("Date1", ((JTextField) Zdate.getDateEditor().getUiComponent()).getText());
                parametre.put("Date2", ((JTextField) Zdate1.getDateEditor().getUiComponent()).getText());
                parametre.put("Prod", cmbprod.getSelectedItem().toString());
                JasperPrint jp = JasperFillManager.fillReport(jr, parametre, con);
                JRViewer viewer = new JRViewer(jp);
                viewer.setOpaque(true);
                viewer.setVisible(true);
                F_ListProd Lprod = new F_ListProd(new javax.swing.JFrame(), true);
                Lprod.jScrollPane1.add(viewer);
                Lprod.jScrollPane1.setViewportView(viewer);
                Lprod.setVisible(true);
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, "Erreur d'élaboration de rapport d'entrée.", "JStore : Erreur", JOptionPane.ERROR_MESSAGE);
            }
        }else if (DateInf == true && Fournis == false && Produit == true) {
            try {
                con = new ConnectDataBase().getConnetion();
                String report = "D:\\jkl\\Logiciel\\java\\jordie\\mes application java\\JStore\\src\\EtatSortie\\EntDateInfProd.jrxml";
                JasperReport jr = JasperCompileManager.compileReport(report);
                Map parametre = new HashMap();
                parametre.put("DateInf", ((JTextField) Zdate.getDateEditor().getUiComponent()).getText());
                parametre.put("Prod", cmbprod.getSelectedItem().toString());
                JasperPrint jp = JasperFillManager.fillReport(jr, parametre, con);
                JRViewer viewer = new JRViewer(jp);
                viewer.setOpaque(true);
                viewer.setVisible(true);
                F_ListProd Lprod = new F_ListProd(new javax.swing.JFrame(), true);
                Lprod.jScrollPane1.add(viewer);
                Lprod.jScrollPane1.setViewportView(viewer);
                Lprod.setVisible(true);
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, "Erreur d'élaboration de rapport d'entrée.", "JStore : Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } else if (UneDate == true && Fournis == true && Produit == true) {
            try {
                con = new ConnectDataBase().getConnetion();
                String report = "D:\\jkl\\Logiciel\\java\\jordie\\mes application java\\JStore\\src\\EtatSortie\\EntUneDateFourProd.jrxml";
                JasperReport jr = JasperCompileManager.compileReport(report);
                Map parametre = new HashMap();
                parametre.put("UneDate", ((JTextField) Zdate.getDateEditor().getUiComponent()).getText());
                parametre.put("Four", cmbfour.getSelectedItem().toString());
                parametre.put("Prod", cmbprod.getSelectedItem().toString());
                JasperPrint jp = JasperFillManager.fillReport(jr, parametre, con);
                JRViewer viewer = new JRViewer(jp);
                viewer.setOpaque(true);
                viewer.setVisible(true);
                F_ListProd Lprod = new F_ListProd(new javax.swing.JFrame(), true);
                Lprod.jScrollPane1.add(viewer);
                Lprod.jScrollPane1.setViewportView(viewer);
                Lprod.setVisible(true);
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, "Erreur d'élaboration de rapport d'entrée.", "JStore : Erreur", JOptionPane.ERROR_MESSAGE);
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        /*
         * ControleurVueEntree c = new ControleurVueEntree(((JTextField)
         * Zdate.getDateEditor().getUiComponent()).getText(), ((JTextField)
         * Zdate1.getDateEditor().getUiComponent()).getText(), UneDate,
         * DeuxDate, DateInf, DateSup, Fournis, Produit, "", "");
         * c.remplirTableau();
         */
        RemplirFournisseur();
        RemplirProduit();
        //TabEntrer.setModel(c.getDtm());
        Zdate.setEnabled(false);
        Zdate1.setEnabled(false);
        jButton1.setEnabled(false);
        cmbfour.setEnabled(false);
        cmbprod.setEnabled(false);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void radProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radProdActionPerformed
        if (radProd.isSelected()) {
            Produit = true;
            cmbprod.setEnabled(true);
        } else {
            Produit = false;
            cmbprod.setEnabled(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_radProdActionPerformed

    private void rad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad1ActionPerformed
        if (rad1.isSelected()) {
            rad2.setSelected(false);
            rad3.setSelected(false);
            rad4.setSelected(false);
            UneDate = true;
            DeuxDate = false;
            DateInf = false;
            DateSup = false;
            Zdate.setEnabled(true);
            jButton1.setEnabled(true);
            Zdate1.setEnabled(false);
        } else {
            Zdate.setEnabled(false);
            Zdate1.setEnabled(false);
            jButton1.setEnabled(false);
            UneDate = false;
            DeuxDate = false;
            DateInf = false;
            DateSup = false;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_rad1ActionPerformed

    private void rad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad3ActionPerformed
        if (rad3.isSelected()) {
            rad1.setSelected(false);
            rad2.setSelected(false);
            rad4.setSelected(false);
            UneDate = false;
            DeuxDate = false;
            DateInf = true;
            DateSup = false;
            Zdate1.setEnabled(false);
            Zdate.setEnabled(true);
            jButton1.setEnabled(true);
        } else {
            UneDate = false;
            DeuxDate = false;
            DateInf = false;
            DateSup = false;
            Zdate.setEnabled(false);
            Zdate1.setEnabled(false);
            jButton1.setEnabled(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_rad3ActionPerformed

    private void rad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad2ActionPerformed
        if (rad2.isSelected()) {
            rad1.setSelected(false);
            rad3.setSelected(false);
            rad4.setSelected(false);
            UneDate = false;
            DeuxDate = true;
            DateInf = false;
            DateSup = false;
            Zdate1.setEnabled(true);
            Zdate.setEnabled(true);
            jButton1.setEnabled(true);
        } else {
            UneDate = false;
            DeuxDate = false;
            DateInf = false;
            DateSup = false;
            Zdate.setEnabled(false);
            Zdate1.setEnabled(false);
            jButton1.setEnabled(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_rad2ActionPerformed

    private void radFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radFourActionPerformed
        if (radFour.isSelected()) {
            Fournis = true;
            cmbfour.setEnabled(true);
        } else {
            Fournis = false;
            cmbfour.setEnabled(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_radFourActionPerformed

    private void rad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad4ActionPerformed
        if (rad4.isSelected()) {
            rad1.setSelected(false);
            rad2.setSelected(false);
            rad3.setSelected(false);
            UneDate = false;
            DeuxDate = false;
            DateInf = false;
            DateSup = true;
            Zdate.setEnabled(true);
            Zdate1.setEnabled(false);
            jButton1.setEnabled(true);
        } else {
            Zdate1.setEnabled(true);
            UneDate = false;
            DeuxDate = false;
            DateInf = false;
            DateSup = false;
            Zdate.setEnabled(false);
            Zdate1.setEnabled(false);
            jButton1.setEnabled(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_rad4ActionPerformed

    public void RemplirFournisseur() {
        try {
            String reqver = "SELECT * FROM t_fourn";
            st = new ConnectDataBase().getConnetion().createStatement();
            rs = st.executeQuery(reqver);
            while (rs.next()) {
                cmbfour.addItem(rs.getString("nomsfour"));
            }
        } catch (SQLException ex) {
            System.out.print(ex);
        }
    }

    public void RemplirProduit() {
        try {
            String reqver = "SELECT * FROM t_article";
            st = new ConnectDataBase().getConnetion().createStatement();
            rs = st.executeQuery(reqver);
            while (rs.next()) {
                cmbprod.addItem(rs.getString("design"));
            }
        } catch (SQLException ex) {
            System.out.print(ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_optRechEnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_optRechEnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_optRechEnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_optRechEnt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                F_optRechEnt dialog = new F_optRechEnt(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabEntrer;
    private com.toedter.calendar.JDateChooser Zdate;
    private com.toedter.calendar.JDateChooser Zdate1;
    private javax.swing.JComboBox cmbfour;
    private javax.swing.JComboBox cmbprod;
    private picturepanel.ImagePanel imagePanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rad1;
    private javax.swing.JRadioButton rad2;
    private javax.swing.JRadioButton rad3;
    private javax.swing.JRadioButton rad4;
    private javax.swing.JRadioButton radFour;
    private javax.swing.JRadioButton radProd;
    // End of variables declaration//GEN-END:variables
}
