/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import ConnectDataBase.ConnectDataBase;
import Controleur.ControleurTailleMaximale;
import Controleur.ControleurVueEntree;
import Controleur.SubJTable;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Pascal_De_Marie
 */
public class F_ventree extends javax.swing.JDialog {

    boolean UneDate = false, DeuxDate = false, DateInf = false, DateSup = false, Fournis = false, Produit = false;
    private Statement st;
    private ResultSet rs;

    /**
     * Creates new form F_ventree
     */
    public F_ventree(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(Color.white);
        //imagePanel1.setImage(new ImageIcon(this.getClass().getResource("/Icons/B1.PNG")).getImage());
        this.setIconImage(new ImageIcon(getClass().getResource("/Icons/viewoptions.png")).getImage());
        ControleurTailleMaximale c = new ControleurTailleMaximale();
        setLocationRelativeTo(null);
        //c.TailleMaximale();
        //this.setSize(c.xsize, c.ysize);
        TabEntrer.setDefaultRenderer(Object.class, new SubJTable());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel1 = new picturepanel.ImagePanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        rad1 = new javax.swing.JRadioButton();
        rad3 = new javax.swing.JRadioButton();
        rad4 = new javax.swing.JRadioButton();
        rad2 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        radFour = new javax.swing.JRadioButton();
        cmbfour = new javax.swing.JComboBox();
        radProd = new javax.swing.JRadioButton();
        cmbprod = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Zdate = new com.toedter.calendar.JDateChooser();
        Zdate1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabEntrer = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        setForeground(new java.awt.Color(0, 102, 153));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        jPanel1.setOpaque(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setOpaque(false);

        rad1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rad1.setText("Une date");
        rad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad1ActionPerformed(evt);
            }
        });

        rad3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rad3.setText("Avant une date");
        rad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad3ActionPerformed(evt);
            }
        });

        rad4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rad4.setText("Après une date");
        rad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad4ActionPerformed(evt);
            }
        });

        rad2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rad2.setText("Entre deux dates");
        rad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rad1)
                    .addComponent(rad3)
                    .addComponent(rad4)
                    .addComponent(rad2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rad1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rad3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rad4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rad2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setOpaque(false);

        radFour.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        radFour.setText("Fournisseur :");
        radFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radFourActionPerformed(evt);
            }
        });

        cmbfour.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));

        radProd.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        radProd.setText("Produit :");
        radProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radProdActionPerformed(evt);
            }
        });

        cmbprod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(radFour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbfour, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(radProd)
                        .addGap(24, 24, 24)
                        .addComponent(cmbprod, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radFour)
                    .addComponent(cmbfour, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radProd)
                    .addComponent(cmbprod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel1.setText("Du :");

        Zdate.setForeground(new java.awt.Color(0, 102, 102));
        Zdate.setDateFormatString("yyyy-MM-dd");
        Zdate.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Zdate.setOpaque(false);

        Zdate1.setForeground(new java.awt.Color(0, 102, 102));
        Zdate1.setDateFormatString("yyyy-MM-dd");
        Zdate1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Zdate1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setText("Au :");

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/1623.png"))); // NOI18N
        jButton1.setText("Rechercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 204));
        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/redo.png"))); // NOI18N
        jButton2.setText("Actueliser");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Zdate, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Zdate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Zdate, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Zdate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabEntrer.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TabEntrer.setForeground(new java.awt.Color(0, 102, 153));
        TabEntrer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro d'entrée", "Date d'entrée", "Quantité", "Prix unitaire", "Fournisseur", "Article"
            }
        ));
        jScrollPane1.setViewportView(TabEntrer);

        javax.swing.GroupLayout imagePanel1Layout = new javax.swing.GroupLayout(imagePanel1);
        imagePanel1.setLayout(imagePanel1Layout);
        imagePanel1Layout.setHorizontalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        imagePanel1Layout.setVerticalGroup(
            imagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ControleurVueEntree c = new ControleurVueEntree(((JTextField) Zdate.getDateEditor().getUiComponent()).getText(), ((JTextField) Zdate1.getDateEditor().getUiComponent()).getText(), UneDate, DeuxDate, DateInf, DateSup, Fournis, Produit, "", "");
        c.remplirTableau();
        RemplirFournisseur();
        RemplirProduit();
        TabEntrer.setModel(c.getDtm());
        Zdate.setEnabled(false);
        Zdate1.setEnabled(false);
        jButton1.setEnabled(false);
        cmbfour.setEnabled(false);
        cmbprod.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ControleurVueEntree c = new ControleurVueEntree(((JTextField) Zdate.getDateEditor().getUiComponent()).getText(), ((JTextField) Zdate1.getDateEditor().getUiComponent()).getText(), UneDate, DeuxDate, DateInf, DateSup, Fournis, Produit, cmbfour.getSelectedItem().toString(), cmbprod.getSelectedItem().toString());
        c.Rechercher();
        TabEntrer.setModel(c.getDtm());        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ControleurVueEntree c = new ControleurVueEntree(((JTextField) Zdate.getDateEditor().getUiComponent()).getText(), ((JTextField) Zdate1.getDateEditor().getUiComponent()).getText(), UneDate, DeuxDate, DateInf, DateSup, Fournis, Produit, "", "");
        c.remplirTableau();
        TabEntrer.setModel(c.getDtm());
        ((JTextField) Zdate.getDateEditor().getUiComponent()).setText(null);
        ((JTextField) Zdate1.getDateEditor().getUiComponent()).setText(null);
        Zdate.setEnabled(false);
        Zdate1.setEnabled(false);
        jButton1.setEnabled(false);
        cmbfour.setSelectedIndex(0);
        cmbfour.setEnabled(false);
        cmbprod.setSelectedIndex(0);
        cmbprod.setEnabled(false);
        rad1.setSelected(false);
        rad2.setSelected(false);
        rad3.setSelected(false);
        rad4.setSelected(false);
        radFour.setSelected(false);
        radProd.setSelected(false);
        UneDate = true;
        DeuxDate = false;
        DateInf = false;
        DateSup = false;
        Fournis = false;
        Produit = false;
        ((JTextField) Zdate.getDateEditor().getUiComponent()).requestFocus();       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad1ActionPerformed
        if (rad1.isSelected()) {
            rad2.setSelected(false);
            rad3.setSelected(false);
            rad4.setSelected(false);
            UneDate = true;
            DeuxDate = false;
            DateInf = false;
            DateSup = false;
            Zdate.setEnabled(true);
            jButton1.setEnabled(true);
            Zdate1.setEnabled(false);
        } else {
            Zdate.setEnabled(false);
            Zdate1.setEnabled(false);
            jButton1.setEnabled(false);
            UneDate = false;
            DeuxDate = false;
            DateInf = false;
            DateSup = false;
        }// TODO add your handling code here:
    }//GEN-LAST:event_rad1ActionPerformed

    private void rad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad2ActionPerformed
        if (rad2.isSelected()) {
            rad1.setSelected(false);
            rad3.setSelected(false);
            rad4.setSelected(false);
            UneDate = false;
            DeuxDate = true;
            DateInf = false;
            DateSup = false;
            Zdate1.setEnabled(true);
            Zdate.setEnabled(true);
            jButton1.setEnabled(true);
        } else {
            UneDate = false;
            DeuxDate = false;
            DateInf = false;
            DateSup = false;
            Zdate.setEnabled(false);
            Zdate1.setEnabled(false);
            jButton1.setEnabled(false);
        }// TODO add your handling code here:
    }//GEN-LAST:event_rad2ActionPerformed

    private void rad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad3ActionPerformed
        if (rad3.isSelected()) {
            rad1.setSelected(false);
            rad2.setSelected(false);
            rad4.setSelected(false);
            UneDate = false;
            DeuxDate = false;
            DateInf = true;
            DateSup = false;
            Zdate1.setEnabled(false);
            Zdate.setEnabled(true);
            jButton1.setEnabled(true);
        } else {
            UneDate = false;
            DeuxDate = false;
            DateInf = false;
            DateSup = false;
            Zdate.setEnabled(false);
            Zdate1.setEnabled(false);
            jButton1.setEnabled(false);
        }// TODO add your handling code here:
    }//GEN-LAST:event_rad3ActionPerformed

    private void rad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad4ActionPerformed
        if (rad4.isSelected()) {
            rad1.setSelected(false);
            rad2.setSelected(false);
            rad3.setSelected(false);
            UneDate = false;
            DeuxDate = false;
            DateInf = false;
            DateSup = true;
            Zdate.setEnabled(true);
            Zdate1.setEnabled(false);
            jButton1.setEnabled(true);
        } else {
            Zdate1.setEnabled(true);
            UneDate = false;
            DeuxDate = false;
            DateInf = false;
            DateSup = false;
            Zdate.setEnabled(false);
            Zdate1.setEnabled(false);
            jButton1.setEnabled(false);
        }// TODO add your handling code here:
    }//GEN-LAST:event_rad4ActionPerformed

    private void radFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radFourActionPerformed
        if (radFour.isSelected()) {
            Fournis = true;
            cmbfour.setEnabled(true);
        } else {
            Fournis = false;
            cmbfour.setEnabled(false);
        }// TODO add your handling code here:
    }//GEN-LAST:event_radFourActionPerformed

    private void radProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radProdActionPerformed
        if (radProd.isSelected()) {
            Produit = true;
            cmbprod.setEnabled(true);
        } else {
            Produit = false;
            cmbprod.setEnabled(false);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_radProdActionPerformed

    public void RemplirFournisseur() {
        try {
            String reqver = "SELECT * FROM t_fourn";
            st = new ConnectDataBase().getConnetion().createStatement();
            rs = st.executeQuery(reqver);
            while (rs.next()) {
                cmbfour.addItem(rs.getString("nomsfour"));
            }
        } catch (SQLException ex) {
            System.out.print(ex);
        }
    }

    public void RemplirProduit() {
        try {
            String reqver = "SELECT * FROM t_article";
            st = new ConnectDataBase().getConnetion().createStatement();
            rs = st.executeQuery(reqver);
            while (rs.next()) {
                cmbprod.addItem(rs.getString("design"));
            }
        } catch (SQLException ex) {
            System.out.print(ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_ventree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_ventree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_ventree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_ventree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                F_ventree dialog = new F_ventree(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabEntrer;
    private com.toedter.calendar.JDateChooser Zdate;
    private com.toedter.calendar.JDateChooser Zdate1;
    private javax.swing.JComboBox cmbfour;
    private javax.swing.JComboBox cmbprod;
    private picturepanel.ImagePanel imagePanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rad1;
    private javax.swing.JRadioButton rad2;
    private javax.swing.JRadioButton rad3;
    private javax.swing.JRadioButton rad4;
    private javax.swing.JRadioButton radFour;
    private javax.swing.JRadioButton radProd;
    // End of variables declaration//GEN-END:variables
}
