/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import ConnectDataBase.ConnectDataBase;
import Controleur.ControleurLog;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Pascal_De_Marie
 */
public class Log extends javax.swing.JFrame {

    String type;
    String Noms;
    String Pass;
    Statement st;
    ResultSet rs;
    int i;
    private int mois;
    private int annee;
    private int jour;
    private int seconde;
    private int minute;
    private int heure;
    /**
     * Creates new form Loggin
     */
    public Log() {
        initComponents();
        this.getContentPane().setBackground(Color.white);//userlogin4
        //com.sun.awt.AWTUtilities.setWindowOpacity(this, 0.7f);
        //imagePanel1.setImage(new ImageIcon(this.getClass().getResource("/Icons/b1.PNG")).getImage());
        //imagePanel4.setImage(new ImageIcon(this.getClass().getResource("/Icons/B1.PNG")).getImage());
        imagePanel2.setImage(new ImageIcon(this.getClass().getResource("/Icons/userlogin3.PNG")).getImage());
        imagePanel3.setImage(new ImageIcon(this.getClass().getResource("/Icons/userlogin4.PNG")).getImage());
        this.setIconImage(new ImageIcon(getClass().getResource("/Icons/viewoptions.png")).getImage());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagePanel4 = new picturepanel.ImagePanel();
        imagePanel3 = new picturepanel.ImagePanel();
        Znu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        imagePanel2 = new picturepanel.ImagePanel();
        Ztut = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Zmp = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Ztut1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        setForeground(new java.awt.Color(0, 102, 153));
        setResizable(false);

        javax.swing.GroupLayout imagePanel3Layout = new javax.swing.GroupLayout(imagePanel3);
        imagePanel3.setLayout(imagePanel3Layout);
        imagePanel3Layout.setHorizontalGroup(
            imagePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        imagePanel3Layout.setVerticalGroup(
            imagePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Znu.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setText("Type d'utilisateur :");

        javax.swing.GroupLayout imagePanel2Layout = new javax.swing.GroupLayout(imagePanel2);
        imagePanel2.setLayout(imagePanel2Layout);
        imagePanel2Layout.setHorizontalGroup(
            imagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        imagePanel2Layout.setVerticalGroup(
            imagePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        Ztut.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Ztut.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrateur", "Simple" }));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setText("Mot de passe :");

        jButton1.setBackground(new java.awt.Color(0, 153, 204));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/b_usrcheck.png"))); // NOI18N
        jButton1.setText("Ok");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Zmp.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setText("Nom d'utilisateur :");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setText("Secteur :");

        Ztut1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Ztut1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Post1", "Post2", " " }));

        javax.swing.GroupLayout imagePanel4Layout = new javax.swing.GroupLayout(imagePanel4);
        imagePanel4.setLayout(imagePanel4Layout);
        imagePanel4Layout.setHorizontalGroup(
            imagePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanel4Layout.createSequentialGroup()
                .addGroup(imagePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imagePanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(imagePanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(imagePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imagePanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imagePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(imagePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Zmp)
                            .addGroup(imagePanel4Layout.createSequentialGroup()
                                .addGroup(imagePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(imagePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Ztut, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Znu, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5)
                                    .addComponent(Ztut1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        imagePanel4Layout.setVerticalGroup(
            imagePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanel4Layout.createSequentialGroup()
                .addGroup(imagePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imagePanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)
                        .addComponent(Ztut1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)
                        .addComponent(Ztut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Znu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Zmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(imagePanel4Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(imagePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(imagePanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imagePanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        type=Ztut.getSelectedItem().toString();
        Noms=Znu.getText();
        Pass=Zmp.getText();
        Log();
        /*ControleurLog c = new ControleurLog(Ztut.getSelectedItem().toString(), Znu.getText(), Zmp.getText());
        c.Log();
        this.setVisible(false);*/// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    public int Numfacture() {
        int numrow = 0;
        try {
            String raqselect = "select max(RowNum) from t_log";
            st = new ConnectDataBase().getConnetion().createStatement();
            rs = st.executeQuery(raqselect);
            if (rs.next()) {
                numrow = 0 + rs.getInt(1);
            }
        } catch (Exception ex) {
            System.out.print(ex);
        }
        return numrow + 1;
    }

    public void dateheure() {
        Thread clock = new Thread() {

            @Override
            public void run() {
                for (;;) {
                    Calendar cal = new GregorianCalendar();
                    mois = cal.get(Calendar.MONTH);
                    annee = cal.get(Calendar.YEAR);
                    jour = cal.get(Calendar.DAY_OF_MONTH);
                    seconde = cal.get(Calendar.SECOND);
                    minute = cal.get(Calendar.MINUTE);
                    heure = cal.get(Calendar.HOUR);
                    try {
                        sleep(1000);
                    } catch (Exception e) {
                    }
                }
            }
        };
        clock.start();
    }
    int tenta=0;
    public void Log() {
        try {
            switch (type) {
                case "Administrateur": {
                    String reqint = "Select * from t_admi where Nomuser='" + Noms + "' and Pass='" + Pass + "'";
                    st = new ConnectDataBase().getConnetion().createStatement();
                    rs = st.executeQuery(reqint);
                    if (rs.next()) {
                        JOptionPane.showMessageDialog(null, "Administrateur identifié.", "JStore : INFORMATION", JOptionPane.INFORMATION_MESSAGE);
                        Menu m=new Menu();
                        m.labus.setText("Utilisateur actuel : "+Noms);
                        m.setVisible(true);
                        this.setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(null, "Administrateur non identifié.", "JStore : ERREUR", JOptionPane.ERROR_MESSAGE);
                        type = "";
                        Noms = "";
                        Pass = "";
                        tenta=tenta+1;
                        if(tenta == 5){
                            JOptionPane.showMessageDialog(null, "Nombre de tentative épuisé.\nJe suis obligé de m'arrêter", "JStore : ERREUR", JOptionPane.ERROR_MESSAGE);
                        System.exit(0);
                        }
                    }
                    break;
                }
                case "Simple": {
                    String reqint = "Select * from t_user where Nomuser='" + Noms + "' and Pass='" + Pass + "'";
                    String ref;
                    st = new ConnectDataBase().getConnetion().createStatement();
                    rs = st.executeQuery(reqint);
                    if (rs.next()) {
                        JOptionPane.showMessageDialog(null, "Utilisateur identifié.", "JStore : INFORMATION", JOptionPane.INFORMATION_MESSAGE);
                        ref = rs.getString("Refuser");
                        String sl = "in";
                        st = new ConnectDataBase().getConnetion().createStatement();
                        st.executeUpdate("Insert into t_log values('" + Numfacture() + "','" + ref + "','" + type + "','" + annee + "-" + (mois + 1) + "-" + jour + " " + heure + ":" + minute + ":" + seconde + "','" + sl + "')");
                        new Log().setVisible(false);
                        Menu m=new Menu();
                        m.labus.setText("Utilisateur actuel : "+Noms);
                        m.jMenu1.setVisible(false);
                        m.jMenu1.setEnabled(false);
                        m.jMenuItem5.setVisible(false);
                        m.jMenuItem5.setEnabled(false);
                        m.jMenu4.setVisible(false);
                        m.jMenu4.setEnabled(false);
                        m.jMenu5.setVisible(false);
                        m.jMenu5.setEnabled(false);
                        m.setVisible(true);
                        this.setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(null, "Uilisateur non identifié.", "JStore : ERREUR", JOptionPane.ERROR_MESSAGE);
                        type = "";
                        Noms = "";
                        Pass = "";
                        if(tenta == 5){
                            JOptionPane.showMessageDialog(null, "Nombre de tentative épuisé.\nJe suis obligé de m'arrêter", "JStore : ERREUR", JOptionPane.ERROR_MESSAGE);
                        System.exit(0);
                        }
                    }
                    break;
                }
            }
        } catch (SQLException e) {
            System.out.print(e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Log().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Zmp;
    private javax.swing.JTextField Znu;
    private javax.swing.JComboBox Ztut;
    private javax.swing.JComboBox Ztut1;
    private picturepanel.ImagePanel imagePanel2;
    private picturepanel.ImagePanel imagePanel3;
    private picturepanel.ImagePanel imagePanel4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
